# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11qEmfIskwAQMM6LfyZdBzKrGZ3S7lfP6
"""

import pandas as pd
from scipy.stats import ttest_ind

# Reading the CSV file
frailty_data = pd.read_csv("/content/clean_frailty_data.csv")


# Conducting t-test
Category_Y = frailty_data[frailty_data['Frailty'] == 'Y']['Weight']
Category_N = frailty_data[frailty_data['Frailty'] == 'N']['Weight']
t_stat, p_value = ttest_ind(Category_Y, Category_N, equal_var=False)

# Printing t-test results
print("T-statistic:", t_stat)
print("P-value:", p_value)

# Writing results to a text file
with open("/content/results.txt", "w") as file:
    file.write(f"T-statistic: {t_stat}\n")
    file.write(f"P-value: {p_value}\n")