# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E7Of9DzcLnffN1GN8AkvQurda45nF_tq
"""



import pandas as pd

# Reading the CSV file
frailty_data = pd.read_csv("/content/raw_frailty_data1.csv")

# Renaming the columns
frailty_data.columns = ['Height', 'Weight', 'Age', 'Grip_Strength', 'Frailty']

# Understanding the data and dimensions
print(frailty_data.shape)

# Getting the top rows
print(frailty_data)

# Getting the summary of the data
print(frailty_data.info())

# Converting 'Frailty' column to categorical
frailty_data['Frailty'] = frailty_data['Frailty'].astype('category')

# Checking for missing values
print(frailty_data.isna().any())

# Writing the cleaned data to a CSV file
frailty_data.to_csv("/content/clean_frailty_data.csv", index=False)

