# -*- coding: utf-8 -*-
"""Preprocesssing2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zBJeH5nRnnt9oeSp7GFefSEEyrY1_9Nf
"""

import pandas as pd

# Reading the given CSV file
Student = pd.read_csv("/content/StudentsPerformance.csv")

print(Student.columns)
print(Student.shape)

#top 5 rows
print(Student.head())

# last 5 rows
print(Student.tail())

print(Student.describe())

print(Student.info())

# Converting columns to categorical
Student['gender'] = pd.Categorical(Student['gender'])
Student['race/ethnicity'] = pd.Categorical(Student['race/ethnicity'])
Student['parental level of education'] = pd.Categorical(Student['parental level of education'])
Student['lunch'] = pd.Categorical(Student['lunch'])
Student['test preparation course'] = pd.Categorical(Student['test preparation course'])

# Removing unnecessary column 'lunch'
Student = Student.drop(columns=['lunch'])

# summary after removing 'lunch' column
print(Student.describe())

# Checking for any missing values
print(Student.isna().any())

# Saving the clean data
Student.to_csv("/content/clean_Students_Data.csv", index=False)