# -*- coding: utf-8 -*-
"""Visualisation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bI6JbE7hdjhZqY2rwl7LrjSPbVXXr5Wg
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Reading the CSV file
Student = pd.read_csv("/content/clean_Students_Data.csv")

# Displaying summary
print(Student.describe())


print(Student.columns)
print(Student.shape)

# Getting the top rows
print(Student.head())

# Scatter plot of math score vs reading score colored by gender
custom_palette = {'male': 'blue', 'female': 'red'}
plt.figure(figsize=(10, 6))
sns.scatterplot(x='math score', y='reading score', hue='gender', data=Student, palette=custom_palette)
plt.title('Correlation Between Math Score & Reading Score')
plt.xlabel('Math Score')
plt.ylabel('Reading Score')
plt.show()

# Distribution plots
plt.figure(figsize=(12, 8))
plt.subplot(2, 2, 1)
sns.histplot(Student['math score'], bins=15, kde=True)
plt.xlabel('Math Score')
plt.title('Distribution of Math Score')

plt.subplot(2, 2, 2)
sns.histplot(Student['reading score'], bins=15, kde=True)
plt.xlabel('Reading Score')
plt.title('Distribution of Reading Score')

plt.subplot(2, 2, 3)
sns.histplot(Student['writing score'], bins=15, kde=True)
plt.xlabel('Writing Score')
plt.title('Distribution of Writing Score')

plt.tight_layout()
plt.show()

# Boxplot of writing score based on Gender
plt.figure(figsize=(8, 6))
sns.boxplot(x='gender', y='writing score', data=Student)
plt.title('Distribution of writing Score Based on Gender')
plt.xlabel('Gender')
plt.ylabel('writing Score')
plt.show()


#Stacked bar plot
plt.figure(figsize=(10, 6))
custom_palette = {'male': 'blue', 'female': 'red'}
sns.countplot(y='race/ethnicity', hue='gender', data=Student, palette=custom_palette)
plt.title('Comparison of Female and Male Students by Race/Ethnicity')
plt.xlabel('Count')
plt.ylabel('Race/Ethnicity')
plt.show()

# Correlation Heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(Student.corr(), annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Heatmap of Student Performance Features')
plt.show()

# Box Plot with Multiple Groups
plt.figure(figsize=(10, 6))
sns.boxplot(x='race/ethnicity', y='math score', hue='gender', data=Student)
plt.title('Distribution of Math Scores Across Race/Ethnicity and Gender')
plt.xlabel('Race/Ethnicity')
plt.ylabel('Math Score')
plt.legend(title='Gender')
plt.show()

# Pairplot
sns.pairplot(Student[['math score', 'reading score', 'writing score']])
plt.suptitle('Pairplot of Math Score, Reading Score, and Writing Score')
plt.show()